### ISSUE TITLE
Path and name of test images

### ISSUE THREAD

**Issue by abderhasan** [YoshiRi/ImRegPOC#2]
Hello Yoshi,

I believe that lines (456-457) in `imregpoc.py`:

```
ref = cv2.imread('../testref1.png',0)
cmp = cv2.imread('../testcmp1.png',0)
```

should be:

```
ref = cv2.imread('ref.png',0)
cmp = cv2.imread('cmp.png',0)
```

In other words, the names of the image files need to be changed, as the ones provided in the code directory have different names than the ones mentioned in the code, and are in the _current directory_ of the code. 

Thanks.
Abder

**Comment by YoshiRi** [comment]
Hello abderhasan.

Thank you for you advice and I fixed this issue.
