### ISSUE TITLE
operands could not be broadcast together with shapes (21500,8192) (8192,21500) 

### ISSUE THREAD

**Issue by joshhu** [YoshiRi/ImRegPOC#4]
![image](https://user-images.githubusercontent.com/10594453/47268490-54ce3680-d584-11e8-8182-edff6a5cfb25.png)

**Comment by tamkaho** [comment]
width, height should be swapped in line 39:

self.hanw = cv2.createHanningWindow((width, height),cv2.CV_64F)

**Comment by YoshiRi** [comment]
line.39 is correct.
I think this error is already corrected by my older update.
Thanks.
