### ISSUE TITLE
Hanning Window Size

### ISSUE THREAD

**Issue by yf-res** [YoshiRi/ImRegPOC#7]
The algorithm assumes that the width and height are equals.
you need to modify as follows:
self.hanw = cv2.createHanningWindow((**width, height**),cv2.CV_64F)  --> **line 40**

**Comment by YoshiRi** [comment]
Thanks for your comments. But I think this problem is already modified two years ago. 
Do you have any other problem?

**Comment by yf-res** [comment]
I probably missed the new change.
Thanks
